<?php

    session_start();
    include("../../../conexion/config/connection.php");
    mysqli_set_charset($conn, "utf8");
    
    $query="SELECT a.*, DATE_FORMAT(a.fecha_venc, '%d/%m/%Y') AS fecha_vencimiento, DATE_FORMAT(b.fecha_insertado, '%d/%m/%Y') AS fecha_notif, DATE_FORMAT(b.fecha_insertado, '%H:%i:%s %p') AS hora_notif, b.id_notificacion, b.estado_notificacion
            FROM id18070131_sivenpro.productos a
            INNER JOIN id18070131_sivenpro.notificaciones b ON b.id_producto = a.id_producto
            WHERE a.estado = 'Activo'
            AND b.estado_notificacion = 'Activo'
            ORDER BY fecha_notif ASC, hora_notif ASC";

    $cantidad_datos=0;
    $resultado = mysqli_query($conn, $query);

    if(!$resultado){ die("Error en la consulta!");
    }else{
        while ($data = mysqli_fetch_assoc($resultado)){
          $cantidad_datos++;

          $id = $data['id_notificacion'];

          if($data['imagen_ref']=="" || $data['imagen_ref']==null){
            $imagen= "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAMCAggICAgICAgGCAgICAgICAgICAgHBwYICAgICAgIBggICAYICAgICAgICAoIBggICQkKBggLDQoIDQYICQgBAwQEAgICCQICCQgCAgIICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICP/AABEIAYACAAMBEQACEQEDEQH/xAAcAAEAAwEBAQEBAAAAAAAAAAAABQYHBAEDAgn/xABEEAACAQIBBwUOBAYBBQEAAAAAAQIDESEEBQYSMUFRB1NhcYETFhciMzRykaGxssHR0jJzkqIkQlJigvDCI5Ph4vFD/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AP6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwFwFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPzVkkm20kldt7Elt9gFMr8psE2oU5Tjulr6l+lLVlh1+oD5+FBczL/uf+gDwoLmZf8Ac/8ARe9AW/NmcI1YRqQd4tcLNPfF9TwuB1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABw59yaU6NWEVeUoSUVxdsNuG3iBm/eLlPNro8eP1Ad4uU82v1x+oB6C5Vza/XH6gXfQrNdSjRcaitLXbSupeLqx4NrbfACfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPxVrJJybso4tvBLre7tAreWcoeTxdo69Tpiko9jk4pgc3hNpc1X/Z94Dwm0uar/s+8B4TaXNV/wBn3gPCbS5qv+z7wHhNpc1X/Z94Dwm0uar/ALPvAeE2lzVf9n3gPCbS5qv+z7wHhNpc1X/Z94Dwm0uar/s+8B4TaXNV/wBn3gPCbS5qv+z7wHhNpc1X/Z94Dwm0uar/ALPvAeE2lzVf9n3gPCbS5qv+z7wHhNpc1X/Z94Dwm0uar/s+8D75Jyi0JO0lUhja8lFrt1ZSa9QFloZQpJOLTT2NNNPtQH0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyT/8AvADKtK9JZVpuKbVKLajHZrY4ynxvuT2doEA2B5q9QDV6gGr1ANXqAavUA1eoBq9QDV6gGr1ANXqAavUA1eoBq9QDV6gGr1ANXqAavUAt1AegTei2kMqFRY/9OTtOO5J71wlF44bcVvA1inK6TWxpWfFPH5gfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARmk1Zxyes1zclw/F4vzAx0AAAAAPGwPrk+TSnhCMpPoTfuTA7oaN5Q/8A8a36X/vsA+OUZmrQV5U6keuMvokBxtf7a1gAAAAAASWR6N16i1oUpyjueFn1NuN+wD795uVczP1w+8B3m5VzM/XD7wHeblXMz9cPvA5M4ZjrUknUpzinvdrdrTkkBwgEBrWhuW90yalJ3uk4Y79SUoL2JATYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiNLfNq3o/NAZCAAAAJHM2YKtd+IlZPxpSwiu3e+hAX/NGgtGlZyXdJcZW1Vvwjsw4vhs3AWKjTsrJJLgsF6kB+wCAjc46P0qv46cX/AHLxZfqWPrTApOfOT6cLyot1Ir+Vrx0uCt+Lr29AFSfDeAAAfuhBOUU9jkk+ptIDcIRtglhuXDoA/VgFgFgODPtJOjWTV06U+xqMgMYA9A1TQLzWHpVPjkBYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEaW+bVvR+aAyEAAAndFtGHlEru6pxfjS3vojtxA1PJ8ljCKjFKMUrJLD18X0sD6RQHoAAAAWAqelmh6qp1KaiqqWKWHdbfPg0Bm0lbDhu3rofSAA/VGpZp8Gn12dwNpyLOMKkVOEotPp2dD4NbGugD7906vWA7p1esB3Tq9YEXpLnWFOjU1pRvKEoxjfxpNxaVlvxAyAD0DVNAvNYelU+OQFhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERpb5tW9H5oDIQAH3zbkLqzjTjtk7Lfbi+pAbHm/NsaUIwhbVisOni30tgdYAAAAAAAHkkBn3KBmHVfdorCTtPok9ku3YBTAAHlgGqA1QGqASA9AAapoF5rD0qnxyAsIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiNLfNq3o/NAZCAAu/JrmxN1Kr3eJF9O127LAX4AAAAAAAAAA487ZvVWnOm/542XRLcBi8o2we1bfW/oB4AAAAAAAAA1TQLzWHpVPjkBYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEaW+bVvR+aAyEABqmgmS6uTQf9TlJ9srL2JICwgAAAAAAAAABgY7pPk6jlFZJWSm7dTUZfMCMAAAAAAAAAapoF5rD0qnxyAsIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiNLfNq3o/NAZCAA1zRCpfJqPoW/cwJkAAAAAAAAAAAZHpk/wCKrdcfXqRuBDAAAAAAAAANU0C81h6VT45AWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARGlvm1b0fmgMhAAadyfZVrUNXfCcl2Ntr3+wCzgAAAAAAAAAADFs85Z3SrUn/VNtdWxexX7QOMAAAAAAAABqmgXmsPSqfHICwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACI0t82rej80BkIAC1cn+dtSq6bvaqrLGyU07p8Pw4AaUmB6AAAAAAAAAhtLM6dxoyknaUvFhjZ3e9dSvj1cAMiA9AAAAAAAAAapoF5rD0qnxyAsIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiNLfNq3o/NAZCAA9pys01g9z4Pc/WBrWi+flXpp3WvFWmt9+NuEuO5gTQAAAAAAAH5nNJXbSSxbexJcQMp0u0g7vU8XycLxh08ZdvuAggAAAAAAdObM3SqzjThZuXF2S4t9CWLAtPgzqc7T9UgHgyqc7T9UgLho5mp0KSpyabTk7q6TUm5LaukCTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERpb5tW9H5oDIQAADqzZnOdGanB2a28JL+mXQBqWj+lFPKFh4s0sYN3fS4cU+gCXUwP0AAAAPllGVRgnKTUYrFt4JL/eAGcaWaZutenTuqW+W+p9F0dQFWuAAAAAAAB05Bl8qUlUg7OL28VvT6JLBoCweEqvt1aH6ZfeB54Sq/Ch+mX3oC7aLZ2lXoxqS1VJuSajgsJNLBuTxS3sCXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERpb5tW9H5oDIQAAAB+qdVppptNbGsGupgWzNPKHUjhVj3RL+ZeLPtex+8Cy5Hp1k8rXk4PhNNe1KSAkO+XJ+eo/rX0QHyyjS3JorysH0RvP4UwILL+UmCwpQlJ/1SWrG/Vi322Apmd891a7vUk3bZHZGN+C+oHBYD0AAAAAAACQ0dr0414Oqk4KSvfYr7G+hMDSVpXkvOw9v0A9768l52n7foBJZvyyFSKlBxlB7GtnT/tkB0gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgz7kfdKNWCveVOSVv6tsfakBjDeNuvsa3MD0AAAAAAAAAAAAAAAAAAAAAAB43/v+3A2LRnIu50KcHt1dZ9c/Gd+nECUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHjQFD0y0Ok5OrRjdPGcFe99rlFY3vvX0Aoy6fo11gegAAAAAAAAAAAAAAAAAAAA8l/v/gC6aI6FybVWtFxjF3hDfN7U5bLRXDa3xTA0CIH6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYDjy7M1Gp+OnTk+Litb9SSftA5O9HJuZh7fqA70sm5mHt+oDvSybmYe36gO9LJuZh7fqA70sm5mHt+oDvSybmYe36gO9LJuZh7fqA70sm5mHt+oDvSybmYe36gO9LJuZh7fqA70sm5mHt+oDvSybmYe36gO9LJuZh7fqA70sm5mHt+oDvSybmYe36gO9LJuZh7fqA70sm5mHt+oDvSybmYe36gdOR5io0/wUqSd731U5dkndrsYHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4c6Z3jRg5zwSwwV23ZtKK3t2e22x8AKXlHKXUf4KdNLdrNydumzgvUwOvM2n9SpUhTlSg9eSjeLatfe074LoYFi0jzw6FJ1IqMmpRVm7J3tjhfjsAjdF9LpZRNxlCEUo61023tS2PrA/WlOlksnlCMYRlrRcsZPCztuTQHx0c037tUdOcYwk1eFm3rW2p332xXGzAnc95x7jSnUST1EnZ3Sd5Jdm0CC0Z0zlXqOEqcIpQc7xk5PBxVsV/cBawIzSLOroUnUSUmnFWbssZJbVfjswAiNGtMZV6jhKEIpRcrptvBrc+sDu0q0hlk8YSjGMnKWrZtq1k28Umty3gQeb+UaUqkIypwjGUlFtSfip4X2cfeBd2wKTnLlDlCpOEacJRhJxUnJ+Nquz3YYprsAm9FdInlEZycYx1ZJWTbvdXu72sBONgUnOvKDKFWcI04SUZNXcnd2we6226Ak9FNLHlDnGUVFws0k27p4b1ufACxgfDLMuhTi5TkoxW1u+3cltu+gCm5fymJeTp3W6U3q3/xSbXawOKHKdVvjTpW6HJe3EC5aPZ67vTVTV1L3Vnjs4bAILPunU6NWVNU4SUVF3cnfxknwsBweEupzVP8AVL6ASujWmU69XubhCK1W7ptvC25gfvSjS6WTyhGMIS1ouTbk8MbWwugPNGdNO71HTnGMG1eNm3rW/Esd9sQJrPmcXSpTqJJuKTs3ZPFICE0V0xllFSUHTjBKLlg229mGywFqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUDlNnLWorHVtNrhrXXttb1gfDQNZM1JVVT7o5Yd02ONlhC9lrJ3/wDIFypaP0YTVSFOKkr2ccFjxjez6wI/T/zaXp0/kBXeTPy1T8v/AJID3lN8rT9CXxAViCnSdOawb8aDX9smvfFrqYGh55zoq2QzqLfBXW3Vkpxco/NAVzk3X/Xl+VL4oAaYBXNPvNp9cPjiBV+Tjy8vy5e+IEnyoVPFpR/um/h+oFGqZM0oyWySlbos1cDVlnv+F7vhfublh/Wlb16wGVLJ24ym72i4xvxc217bXAvPJhLxay6ab9euBbM55YqcJ1H/ACRcvou14AZRmDNrrVJR2vUqS65JPVv1ycUB06HZx7nlEOErwl1S2X6nq+0DWJSAy7TnPTnWcE/EpPV/yX4n1q+r/iBMaK6FU3CNWtFycleMNkYrc5Ws23txwxAsk9E8mas6NPsTi+xxswO3N2QRpQjTirRjgt+1t9e/eBmGnHnM+lQXrikBbMx5kySVGlKcKWs4RcrvG9sb+MvcBL5uzRk8Ja1KNNSs03F3dnu2y2gVDlK8rT/LfvYFXhr0nTmsG7ThLdhJr2NO/WBomds6KtkU6iw1oq8f6XrK6fTf3gV3k28rL8p++AGlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/PeZYV4ak+lxlheD2XV/d9AM6zroRWp3aSqxV/Ghi7f3ReP6QPzo3pXUoyipNypN2lGTb1VvcODW22yyYFy0+f8LL06fbsx7QK9yZ+Wqfl/wDJAOU/ylP0JfEB+6eZ3VyCnJfjpupJf3R15a0fU9bs6QITNGc1GlXpP8NSGtHhrRs8PSSAk+TnziX5Uvih8wNLArmn3m0+uHxxAq/Jx5eX5cvfEDr5UJ+PRXRN+2H09gEZlmQ3yGjUt+GpUT6pycfkgPlPO/8AB9xTx7s+2FlL1az9gHTWzfq5vUntqVYy/wAcVH2eN/kBI8mMvGrdUPfICS5Rcu1aKhvqTX6Y2fvt/rArGhmfqeTucpqTclFLVV8E7t7rO4ELl1ZOpOULpOblG6s1d3V1usBsea8sVSnGotk4p9V8Gux3Ax3PMX3Wsnt7pUT69d+8DYcgmnThJbHCLX6VgBl+dMnyqn403XjFyaTc5YvalhJ7v9wAsvJxlMpKtrSnKzhbWk5Wvrcb8EBXdOF/FT6ofCv/AL2Ae5HoNXqQjNKnaaUleSTs9l8HuAtOhWjFShKo6molKKS1XfG+/BcQIjlM8rT/AC5e9gevM3dcgpyivHpOc0v6o67Uo+rFdQENmnOWrSyik3hUhePBTjiv1JY9QEpyc+Wl+U/fADSQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFd0n0teTyppRUtbWcle2Ca2PjdsCO8JlK1+51dbcrxt2yuvcBSqWTyr1bJLWqSbtHdrPG/CKW9gaHp5G2StcJUvkBXuTPy1T8v8A5ID3lO8rT9CXxAWPQNfw0Oup8T9m0Ck6YZk7jVdl4k7yh0J7V2PBdAHbyceXl+VL4oAaWBXNPvNp9cPjiBV+Tjy8vy5e+IH15S6v/WguFNv1uX0Alc1Zt7pm/U2twm11qUpL3W7QM+yai5uMVtm0l/lgBpGmuSKGSaiwUHSiuy0QITkymlUq/lp+qW0Dk5QMv18o1d1Jav8Ak8ZPr2LsAmswaD0p0YTqd0cpLWdpWVm3q2Vna6V+0CD0y0bjQlB09bVkv5ne0o7UnhtQFk5OcvvRlTbu6csPRls9qYENp1o+41HWjFuE/wAdsdWXF8FLDtbA5tG9NZUFqSjrwV7WfjQvuW5pcGB9NLNLIZRCMIxmtWaleVle0WrW7QJHkylhX66fumBB6bv+Kn1Q+ECZzVygwp0qdN06jcIKLacbOy3ATGZtOoVqkaapzi5XxbTSsm93UBAcpflKf5cvewLLoPH+Gp8PH7fHkBRdLsy9xqtJeJPxoP4l2P3gSPJx5af5b+KAGkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIzOeYKVe3dIXaVk7uLS27U1vfSBD+DmhfbW6tdW+ACczXmOlR8nBJ75N60n2vED6ZzzZCtBwmm4tp4Ozutjv8gOPNGjNKhJypqaclqtuV7LbguNwP1nbRmlXalUUm4qytJrB4vZht4tAdebM3QpQUIJqKva7u8cXjjfED4Z1zLCulGom0ndWdmn0PDbwA+GatFqNCTnTU1JxccZOWDafVfBbwJgDkzpmyNaDhNNxbV7Ozwd1iunjYDizTotRoy1qamm1qtuV0k9uHYgPM7aK0a0teopOVrYSaVseCfFgduQ5BGnCMIJqMdl3d7b+8DiybRShCSnGmlJO6d27Pild+4Dszjm2NaDpzvqu29rFO6xSbA5c0aL0aMnOnGSbjqu8tZWunsb6NwHLlOg2TzlKUlUbk229d4t7eAE9RpqKUUrJJJdCWCXsA4s75mhXSjUUmk7qzs0+tbuh2A+OadGqVBuVNTTas7yutt9nWBJyhdbF1P3Pj2gQWVaD5PPHUcb/0ScbdSxXsA+EOTzJk72qPrm/kl7wJzN+aKdJNU4KKdr22u17Xd3xfrAjs5aHUKs3Ump6zsnabWzBYYLZ0gc3g/wAm/pqfrf1A6M3aIUaU1OCmpK9rybWKs8OoD7520ZpV2pVFK8VZWk1h/iniB2ZtzdGlBQhdRV7Ju7xd3j1gfHO+ZKddKNRNpO6aeq0+HUBz5p0XpUJOVNSTa1XeTeG3BbOG/cBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2Q==";
          }else{
            $imagen= $data['imagen_ref'];
          }


          echo $texto =
            '<div class="modal-body">
              <div class="row">
                <div class="col-3">
                  <p class="text-center">
                    <img class="foto-notificacion" src="data:image/png;base64,'.$imagen.'">
                  </p>
                </div>
                
                <div class="col-9">
                  <p>El producto <span class="badge badge-pill badge-info">'.$data["nombre_producto"].'</span>,
                  código <span class="badge badge-pill badge-warning">'.$data["cod_producto"].'</span>
                  está pronto a cumplir la <strong>fecha de vencimiento</strong> establecida para el <span class="break"><strong>'.$data["fecha_vencimiento"].'</span></strong>.
                  <p>
                    <strong>¡Se recomienda tomar acciones preventivas!</strong>
                    <br>PRECIO REFERENCIAL: <strong>$'.$data["precio"].'</strong>
                  </p>
                  <h6>
                    <i class="ti-time"></i> Recibido el '.$data["fecha_notif"].' a las '.$data["hora_notif"].'    
                    <button type="button" rel="tooltip" class="btn btn-danger dlt_notifa" style="margin: 0 !important;padding: 7px !important; float:right;" title="Descartar" onclick="descartarNotificacion('.$id.')">
                      <i class="material-icons">delete</i>
                    </button>
                  </h6>
                </div>
              </div>
            </div>
            <hr size="2px" width="100%" noshade="noshade" align="right" />';
        }
        

        if ($cantidad_datos==0) {
          echo $texto =
          '<li">
            <div style="text-align:center;">
              <h4><strong>Actualmente no posee notificaciones...</strong></h4>
              <p>
                <img src="https://9044c4.medialib.edu.glogster.com/VAzsr0mPpG8jtnLal4Di/media/a7/a7cb9087ae050db7d838fdbdb126ddac75f7e3df/wp42cbc27e.gif" alt="this slowpoke moves" width="250"/>
              </p>
            </div>
          </li>';
        }

        //echo json_encode($arreglo);
        mysqli_free_result($resultado);
        mysqli_close($conn);
    }

?>